apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-toolkit-config
  namespace: default
data:
  URL_MAP: |
    {
      "Config Server Actuator": "/config/actuator/health",
      "Config for Order API ": "/config/order-service/dev",
      "Config for Customer API": "/config/customer-service/default/main",
      "Config for Gateway": "/config/gateway-service/default/main",
      "Config for Discovery": "/config/discovery-service/default/main",
      "Eureka Dashboard": "/discovery",
      "Eureka Actuator:": "/discovery/actuator/health",
      "Gateway Actuator": "/gateway",
      "Customer Actuator": "/api/customer/actuator/health",
      "Customer Swagger": "/api/customer/swagger-ui/webjars/swagger-ui/index.html",
      "Order Service": "/api/order/actuator/health",
      "Web App": "/web"
    }
  COMMAND_SECTIONS: |
    [
      {
        "title": "App Set up Commands",
        "commands": {
          "cd /c/Amit/Work/code/Java/microservice/microservice-Patterns": "Go to project root",
          "kubectl create namespace microservice 2>/dev/null || true": "Create microservice namespace"
        }
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-toolkit
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: developer-toolkit
  template:
    metadata:
      labels:
        app: developer-toolkit
    spec:
      containers:
      - name: developer-toolkit
        image: gcr.io/YOUR_PROJECT_ID/developer-toolkit:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: developer-toolkit-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: developer-toolkit
  namespace: default
spec:
  selector:
    app: developer-toolkit
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: developer-toolkit-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "YOUR_STATIC_IP_NAME"
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /support
        pathType: Prefix
        backend:
          service:
            name: developer-toolkit
            port:
              number: 80
